[deploy]
bucket = 'cfn-artifacts'
region = 'us-east-1'
stack_name = 'CrdCluster'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:579018833036:certificate/3c1ef9e2-8073-4fa1-9dc2-9744bd23dad4'
NetworkingStack = 'CrdNet'